//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Plan
    {
        public int PlanID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        [JsonIgnore]
        [XmlIgnore]

        public virtual Project Project { get; set; }
        [JsonIgnore]
        [XmlIgnore]
        public virtual Team Team { get; set; }
    }
}
